site_name: Tutorial Vue.js
theme: cinder
nav:
  - Home: index.md
  - Instalación: install.md
  - Arquitectura: architecture.md
  - Estructura del proyecto: structure.md
  - Layout: layout.md
  - Blog navigation: blogNav.md
